In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import os
import pickle

In [2]:
dir_list=["drive","trip","weather"]

In [3]:
path="C:\\Users\\Lenovo\\Desktop\\Sanket_backup\\Mhack\\"

In [19]:
df=pd.read_parquet(r"C:\Users\Lenovo\Desktop\Sanket_backup\Mhack\drive\drive_1557398801351_trip_1557398302922_part-00000-tid-4787120893022696848-4897608f-5b93-42b5-a8ab-e90f5cadf0bf-1853-c000.snappy.parquet",engine="pyarrow")

In [20]:
len(df.columns.tolist())

12

In [21]:
drive_col=df.columns.tolist()
drive_col

['vehicle_id',
 'trip_id',
 'datetime',
 'velocity',
 'accel_x',
 'accel_y',
 'accel_z',
 'engine_coolant_temp',
 'eng_load',
 'fuel_level',
 'iat',
 'rpm']

In [22]:
df=pd.read_parquet(r"C:\Users\Lenovo\Desktop\Sanket_backup\Mhack\trip\trip_1557398259127_part-00000-tid-4787120893022696848-4897608f-5b93-42b5-a8ab-e90f5cadf0bf-1853-c000.snappy.parquet",engine="pyarrow")

In [23]:
len(df.columns.tolist())

6

In [24]:
trip_col=df.columns.tolist()
trip_col

['vehicle_id', 'trip_id', 'datetime', 'lat', 'long', 'velocity']

In [5]:
df=pd.read_parquet(r"C:\Users\Lenovo\Desktop\Sanket_backup\Mhack\weather\part-00000-tid-6948431846308939962-d261a692-da15-442f-8f9f-0021ff4fa635-1006-c000.snappy.parquet",engine="pyarrow")

In [6]:
len(df.columns.tolist())

14

In [7]:
weather_col=df.columns.tolist()
weather_col

['x',
 'y',
 'date',
 'time',
 'lat',
 'lon',
 'temperature_data',
 'temperature_unit',
 'precipitation_data',
 'precipitation_unit',
 'wind_ew_data',
 'wind_ew_unit',
 'wind_ns_data',
 'wind_ns_unit']

In [25]:
df_drive=pd.DataFrame(columns=drive_col)
df_trip=pd.DataFrame(columns=trip_col)
#df_weather=pd.DataFrame(columns=weather_col)

In [26]:
for j in os.listdir(path + "drive"):
    df=pd.read_parquet(path+"drive"+ "\\" +str(j),engine="pyarrow")
    df_drive=pd.concat([df_drive,df],ignore_index=True)

In [27]:
df_drive.shape

(9217528, 12)

In [19]:
df_drive.head()

,vehicle_id,trip_id,datetime,velocity,accel_x,accel_y,accel_z,engine_coolant_temp,eng_load,fuel_level,iat,rpm
0,1000515,db3c08b01205459294bbc91e3f7dfeb6,2017-01-06 23:00:00,0.00,50.0,65.13,87.92,150.70,192.88,118.66,95.0,2107.44
1,1000515,db3c08b01205459294bbc91e3f7dfeb6,2017-01-06 23:00:01,47.49,51.0,72.34,83.78,154.76,196.04,116.69,100.0,2119.17
2,1000515,db3c08b01205459294bbc91e3f7dfeb6,2017-01-06 23:00:02,57.94,50.0,69.20,87.73,165.50,196.01,105.46,90.0,2112.32
3,1000515,db3c08b01205459294bbc91e3f7dfeb6,2017-01-06 23:00:03,57.50,48.0,70.83,84.95,157.32,193.31,110.35,90.0,2092.94
4,1000515,db3c08b01205459294bbc91e3f7dfeb6,2017-01-06 23:00:04,52.29,47.0,70.22,92.90,151.00,189.49,104.25,97.0,2117.87

In [28]:
for j in os.listdir(path + "trip"):
    df=pd.read_parquet(path+"trip"+ "\\" +str(j),engine="pyarrow")
    df_trip=pd.concat([df_trip,df],ignore_index=True)

In [29]:
df_trip.shape

(9217528, 6)

In [18]:
df_trip.head()

,vehicle_id,trip_id,datetime,lat,long,velocity
0,1000504,192637d8a8a841dd85942a5ada12c50a,2017-01-02 21:00:00,32.3125,-85.062500,0.00
1,1000504,192637d8a8a841dd85942a5ada12c50a,2017-01-02 21:00:01,32.3125,-85.062222,59.88
2,1000504,192637d8a8a841dd85942a5ada12c50a,2017-01-02 21:00:02,32.3125,-85.061944,76.93
3,1000504,192637d8a8a841dd85942a5ada12c50a,2017-01-02 21:00:03,32.3125,-85.061667,75.10
4,1000504,192637d8a8a841dd85942a5ada12c50a,2017-01-02 21:00:04,32.3125,-85.061389,48.01

In [11]:
weather_list=os.listdir(path + "weather")
len(weather_list)

200

In [12]:
for i in range(150):
    df=df=pd.read_parquet(path+"weather"+ "\\" +weather_list[i],engine="pyarrow")
    df_weather=pd.concat([df_weather,df],ignore_index=True)
    print("Inputs operated %i"%i)

Inputs operated 0
Inputs operated 1
Inputs operated 2
Inputs operated 3
Inputs operated 4
Inputs operated 5
Inputs operated 6
Inputs operated 7
Inputs operated 8
Inputs operated 9
Inputs operated 10
Inputs operated 11
Inputs operated 12
Inputs operated 13
Inputs operated 14
Inputs operated 15
Inputs operated 16
Inputs operated 17
Inputs operated 18
Inputs operated 19
Inputs operated 20
Inputs operated 21
Inputs operated 22
Inputs operated 23
Inputs operated 24
Inputs operated 25
Inputs operated 26
Inputs operated 27
Inputs operated 28
Inputs operated 29
Inputs operated 30
Inputs operated 31
Inputs operated 32
Inputs operated 33
Inputs operated 34
Inputs operated 35
Inputs operated 36
Inputs operated 37
Inputs operated 38
Inputs operated 39
Inputs operated 40
Inputs operated 41
Inputs operated 42
Inputs operated 43
Inputs operated 44
Inputs operated 45
Inputs operated 46
Inputs operated 47
Inputs operated 48
Inputs operated 49
Inputs operated 50
Inputs operated 51
Inputs operated 52
Inputs operated 53
Inputs operated 54
Inputs operated 55
Inputs operated 56
Inputs operated 57
Inputs operated 58
Inputs operated 59
Inputs operated 60
Inputs operated 61
Inputs operated 62
Inputs operated 63
Inputs operated 64
Inputs operated 65
Inputs operated 66
Inputs operated 67
Inputs operated 68
Inputs operated 69
Inputs operated 70
Inputs operated 71
Inputs operated 72
Inputs operated 73
Inputs operated 74
Inputs operated 75
Inputs operated 76
Inputs operated 77
Inputs operated 78
Inputs operated 79
Inputs operated 80
Inputs operated 81
Inputs operated 82
Inputs operated 83
Inputs operated 84
Inputs operated 85
Inputs operated 86
Inputs operated 87
Inputs operated 88
Inputs operated 89
Inputs operated 90
Inputs operated 91
Inputs operated 92
Inputs operated 93
Inputs operated 94
Inputs operated 95
Inputs operated 96
Inputs operated 97
Inputs operated 98
Inputs operated 99
Inputs operated 100
Inputs operated 101
Inputs operated 102
Inputs operated 103
Inputs operated 104
Inputs operated 105
Inputs operated 106
Inputs operated 107
Inputs operated 108
Inputs operated 109
Inputs operated 110
Inputs operated 111
Inputs operated 112
Inputs operated 113
Inputs operated 114
Inputs operated 115
Inputs operated 116
Inputs operated 117
Inputs operated 118
Inputs operated 119
Inputs operated 120
Inputs operated 121
Inputs operated 122
Inputs operated 123
Inputs operated 124
Inputs operated 125
Inputs operated 126
Inputs operated 127
Inputs operated 128
Inputs operated 129
Inputs operated 130
Inputs operated 131
Inputs operated 132
Inputs operated 133
Inputs operated 134
Inputs operated 135
Inputs operated 136
Inputs operated 137
Inputs operated 138
Inputs operated 139
Inputs operated 140
Inputs operated 141
Inputs operated 142
Inputs operated 143
Inputs operated 144
Inputs operated 145
Inputs operated 146
Inputs operated 147
Inputs operated 148
Inputs operated 149

In [13]:
for i in range(150,199):
    df=df=pd.read_parquet(path+"weather"+ "\\" +weather_list[i],engine="pyarrow")
    df_weather=pd.concat([df_weather,df],ignore_index=True)
    print("Inputs operated %i"%i)

Inputs operated 150
Inputs operated 151
Inputs operated 152
Inputs operated 153
Inputs operated 154
Inputs operated 155
Inputs operated 156
Inputs operated 157
Inputs operated 158
Inputs operated 159
Inputs operated 160
Inputs operated 161
Inputs operated 162
Inputs operated 163
Inputs operated 164
Inputs operated 165
Inputs operated 166
Inputs operated 167
Inputs operated 168
Inputs operated 169
Inputs operated 170
Inputs operated 171
Inputs operated 172
Inputs operated 173
Inputs operated 174
Inputs operated 175
Inputs operated 176
Inputs operated 177
Inputs operated 178
Inputs operated 179
Inputs operated 180
Inputs operated 181
Inputs operated 182
Inputs operated 183
Inputs operated 184
Inputs operated 185
Inputs operated 186
Inputs operated 187
Inputs operated 188
Inputs operated 189
Inputs operated 190
Inputs operated 191
Inputs operated 192
Inputs operated 193
Inputs operated 194
Inputs operated 195
Inputs operated 196
Inputs operated 197
Inputs operated 198

In [30]:
df_weather

,x,y,date,time,lat,lon,temperature_data,temperature_unit,precipitation_data,precipitation_unit,wind_ew_data,wind_ew_unit,wind_ns_data,wind_ns_unit
0,85,55,2017-02-15,11Z,31.9375,-114.3125,286.430000,k,0.000000,kg/m^2,1.620000,m/s,-2.720000,m/s
1,191,38,2017-02-23,21Z,29.8125,-101.0625,304.960000,k,0.000000,kg/m^2,4.360000,m/s,0.580000,m/s
2,258,60,2017-02-27,16Z,32.5625,-92.6875,287.590000,k,2.450000,kg/m^2,-3.910000,m/s,-1.110000,m/s
3,113,55,2017-01-25,07Z,31.9375,-110.8125,277.800000,k,0.000000,kg/m^2,2.400000,m/s,-1.440000,m/s
4,304,55,2017-02-03,21Z,31.9375,-86.9375,286.010000,k,0.000000,kg/m^2,2.050000,m/s,-5.160000,m/s
5,223,48,2017-01-08,03Z,31.0625,-97.0625,270.610000,k,0.000000,kg/m^2,1.120000,m/s,-1.310000,m/s
6,101,48,2017-02-18,09Z,31.0625,-112.3125,286.900000,k,0.000000,kg/m^2,-3.910000,m/s,9.950000,m/s
7,130,52,2017-02-13,03Z,31.5625,-108.6875,285.080000,k,1.589200,kg/m^2,-7.620000,m/s,2.780000,m/s
8,308,59,2017-01-12,02Z,32.4375,-86.4375,290.040000,k,0.000000,kg/m^2,-0.590000,m/s,5.010000,m/s
9,120,33,2017-01-12,09Z,29.1875,-109.9375,283.070000,k,0.000000,kg/m^2,-2.040000,m/s,-0.430000,m/s
10,80,44,2017-01-19,21Z,30.5625,-114.9375,290.270000,k,0.000000,kg/m^2,-0.900000,m/s,3.110000,m/s
11,244,47,2017-02-04,03Z,30.9375,-94.4375,282.100000,k,0.000000,kg/m^2,-2.430000,m/s,-2.800000,m/s
12,67,55,2017-02-18,13Z,31.9375,-116.5625,283.400000,k,0.000000,kg/m^2,0.800000,m/s,5.250000,m/s
13,267,54,2017-01-05,16Z,31.8125,-91.5625,281.340000,k,0.000000,kg/m^2,0.060000,m/s,0.590000,m/s
14,291,54,2017-02-04,07Z,31.8125,-88.5625,274.220000,k,0.000000,kg/m^2,-2.000000,m/s,-3.750000,m/s
15,283,57,2017-02-21,01Z,32.1875,-89.5625,293.740000,k,0.000000,kg/m^2,-2.200000,m/s,3.690000,m/s
16,107,52,2017-01-02,07Z,31.5625,-111.5625,278.020000,k,0.000000,kg/m^2,0.080000,m/s,4.680000,m/s
17,126,44,2017-01-25,03Z,30.5625,-109.1875,276.000000,k,0.000000,kg/m^2,5.020000,m/s,3.760000,m/s
18,147,59,2017-01-14,01Z,32.4375,-106.5625,288.620000,k,0.000000,kg/m^2,-1.750000,m/s,2.210000,m/s
19,139,41,2017-01-17,19Z,30.1875,-107.5625,285.080000,k,0.000000,kg/m^2,1.160000,m/s,-1.320000,m/s
20,179,31,2017-01-16,18Z,28.9375,-102.5625,282.130000,k,0.000000,kg/m^2,2.060000,m/s,1.820000,m/s
21,324,53,2017-01-12,05Z,31.6875,-84.4375,285.760000,k,0.000000,kg/m^2,-1.330000,m/s,3.240000,m/s
22,136,32,2017-01-24,05Z,29.0625,-107.9375,277.720000,k,0.000000,kg/m^2,5.580000,m/s,3.650000,m/s
23,332,51,2017-01-11,15Z,31.4375,-83.4375,287.770000,k,0.000000,kg/m^2,-0.430000,m/s,3.650000,m/s
24,192,41,2017-02-16,10Z,30.1875,-100.9375,281.250000,k,0.000000,kg/m^2,-0.720000,m/s,1.190000,m/s
25,254,40,2017-02-05,05Z,30.0625,-93.1875,288.020000,k,0.000000,kg/m^2,-1.910000,m/s,1.730000,m/s
26,223,45,2017-01-20,10Z,30.6875,-97.0625,284.850000,k,0.000000,kg/m^2,1.090000,m/s,3.490000,m/s
27,329,56,2017-02-26,19Z,32.0625,-83.8125,288.010000,k,0.000000,kg/m^2,-1.980000,m/s,-1.630000,m/s
28,245,60,2017-01-29,15Z,32.5625,-94.3125,278.680000,k,0.000000,kg/m^2,5.180000,m/s,-1.900000,m/s
29,256,38,2017-01-09,06Z,29.8125,-92.9375,278.320000,k,0.000000,kg/m^2,-3.730000,m/s,-0.280000,m/s
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10533392,102,41,2017-01-25,00Z,30.1875,-112.1875,286.110000,k,0.000000,kg/m^2,4.090000,m/s,-1.000000,m/s
10533393,219,42,2017-02-28,01Z,30.3125,-97.5625,298.950000,k,0.000000,kg/m^2,-1.490000,m/s,5.790000,m/s
10533394,351,56,2017-02-08,14Z,32.0625,-81.0625,291.370000,k,0.000000,kg/m^2,5.400000,m/s,1.820000,m/s
10533395,344,49,2017-02-04,03Z,31.1875,-81.9375,291.390000,k,0.000000,kg/m^2,3.510000,m/s,-3.650000,m/s
10533396,158,43,2017-01-10,23Z,30.4375,-105.1875,293.890000,k,0.000000,kg/m^2,2.590000,m/s,1.240000,m/s
10533397,80,45,2017-01-27,22Z,30.6875,-114.9375,283.350000,k,0.000000,kg/m^2,2.200000,m/s,-12.850000,m/s
10533398,169,38,2017-02-15,03Z,29.8125,-103.8125,282.500000,k,0.037400,kg/m^2,-0.790000,m/s,-4.890000,m/s
10533399,118,48,2017-01-14,14Z,31.0625,-110.1875,281.610000,k,0.000000,kg/m^2,-1.820000,m/s,5.210000,m/s
10533400,340,54,2017-02-17,18Z,31.8125,-82.4375,291.180000,k,0.000000,kg/m^2,2.430000,m/s,0.360000,m/s
10533401,127,58,2017-01-28,03Z,32.3125,-109.0625,273.160000,k,0.000000,kg/m^2,-0.850000,m/s,-3.180000,m/s
10533402,150,42,2017-02-11,21Z,30.3125,-106.1875,299.590000,k,0.000000,kg/m^2,4.760000,m/s,1.540000,m/s
10533403,80,51,2017-01-15,18Z,31.4375,-114.9375,291.060000,k,0.000000,kg/m^2,-0.370000,m/s,2.840000,m/s
10533404,135,56,2017-02-09,23Z,32.0625,-108.0625,295.890000,k,0.000000,kg/m^2,-1.230000,m/s,1.710000,m/s
10533405,173,31,2017-01-14,16Z,28.9375,-103.3125,290.870000,k,0.000000,kg/m^2,-1.580000,m/s,1.700000,m/s
10533406,189,38,2017-01-26,05Z,29.8125,-101.3125,284.650000,k,0.000000,kg/m^2,1.410000,m/s,-2.790000,m/s
10533407,124,50,2017-02-24,16Z,31.3125,-109.4375,279.170000,k,0.000000,kg/m^2,0.520000,m/s,0.090000,m/s
10533408,343,59,2017-01-07,23Z,32.4375,-82.0625,275.040000,k,0.000000,kg/m^2,-0.500000,m/s,-6.470000,m/s
10533409,317,51,2017-01-28,07Z,31.4375,-85.3125,277.030000,k,0.000000,kg/m^2,2.760000,m/s,-1.650000,m/s
10533410,196,48,2017-02-17,20Z,31.0625,-100.4375,292.400000,k,0.000000,kg/m^2,5.470000,m/s,6.130000,m/s
10533411,271,40,2017-02-23,12Z,30.0625,-91.0625,286.850000,k,0.000000,kg/m^2,-0.210000,m/s,0.600000,m/s
10533412,221,60,2017-01-13,23Z,32.5625,-97.3125,290.070000,k,0.000000,kg/m^2,-1.580000,m/s,-0.580000,m/s
10533413,144,60,2017-02-06,04Z,32.5625,-106.9375,285.940000,k,0.000000,kg/m^2,2.110000,m/s,2.440000,m/s
10533414,299,45,2017-01-17,11Z,30.6875,-87.5625,289.490000,k,0.000000,kg/m^2,-1.590000,m/s,2.900000,m/s
10533415,92,55,2017-02-05,00Z,31.9375,-113.4375,295.760000,k,0.000000,kg/m^2,-0.080000,m/s,0.020000,m/s
10533416,199,51,2017-01-12,00Z,31.4375,-100.0625,292.810000,k,0.000000,kg/m^2,1.320000,m/s,4.900000,m/s
10533417,247,59,2017-02-08,05Z,32.4375,-94.0625,288.200000,k,0.000000,kg/m^2,1.780000,m/s,2.890000,m/s
10533418,105,35,2017-02-17,06Z,29.4375,-111.8125,288.540000,k,0.000000,kg/m^2,1.670000,m/s,3.040000,m/s
10533419,226,30,2017-01-18,02Z,28.8125,-96.6875,293.200000,k,0.684400,kg/m^2,-2.980000,m/s,-0.440000,m/s
10533420,344,39,2017-02-06,08Z,29.9375,-81.9375,285.800000,k,0.000000,kg/m^2,1.460000,m/s,-2.420000,m/s
10533421,269,50,2017-02-27,08Z,31.3125,-91.3125,286.250000,k,0.000000,kg/m^2,-1.290000,m/s,4.720000,m/s

In [ ]:
pickle_out = open("dict.pickle","wb")
pickle.dump(df_w, pickle_out)
pickle_out.close()